In [6]:
!pip install numpy

   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
    --------------------------------------- 0.3/12.4 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.4 MB 872.0 kB/s eta 0:00:14
   - -------------------------------------- 0.5/12.4 MB 872.0 kB/s eta 0:00:14
  


[notice] A new release of pip is available: 25.3 -> 26.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [12]:
#CREATING NUMPY ARRAY
import numpy as np
#Crating a rank 1 Array
arr = np.array([1,2,3])
print(arr)
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
#ACCESSING ARRAY INDEX
import numpy as np
arr = np.array([[-1,2,0,4],
                [4,-0.5,6,0],
                [2.6,0,7,8],
                [3,-7,4,2.0]])
#Printing a range of Array
#with the use of slicing method
arr2 = arr[:2,::2]
print("first 2 rows and alternate columns(0and 2):/n",arr2)


[1 2 3]
[[1 2 3]
 [4 5 6]]
first 2 rows and alternate columns(0and 2):/n [[-1.  0.]
 [ 4.  6.]]


In [14]:
#priting element at
#specific Indices
arr3 = arr[[1,1,0,3],
    [3,2,1,0]]
print("/Element at indices(1,3),"
      "(1,2),(0,1),(3,0);/n",arr3)

/Element at indices(1,3),(1,2),(0,1),(3,0);/n [0. 6. 2. 3.]


In [6]:
#BASIC ARRAY OPERATIONS
import numpy as np
#Defining Array 1
a = np.array([[1,2],[3,4]])
#Defining Arrray 2
b =np.array([[4,3],[2,1]])
#Adding 1 to every element
print("Adding 1 to every elemnt:",a+1)
#Subtrating 2 from each element
print("/nSubtracting 2 from each elemnt:",b-2)
#sum of array elemnt
#Performing Binary operations
print("/nArray sum;/n",a+b)

Adding 1 to every elemnt: [[2 3]
 [4 5]]
/nSubtracting 2 from each elemnt: [[ 2  1]
 [ 0 -1]]
/nArray sum;/n [[5 5]
 [5 5]]


In [9]:
#MATHS OPERATIONS ON DATA TYPE ARRAY
import numpy as np

#First Array
arr1 = np.array([[4,7],[2,6]],
                dtype = np.float64)
#second Arraky
arr2 = np.array([[3,6],[2,8]],
                dtype = np.float64)
#Addition of two Array
sum=np.add(arr1,arr2)
print(sum)
#Squares root of Array
Sqrt = np.sqrt(arr1)
print(Sqrt)

#Transpose of Array
Trans_arr = arr1.T
print(Trans_arr)


[[ 7. 13.]
 [ 4. 14.]]
[[2.         2.64575131]
 [1.41421356 2.44948974]]
[[4. 2.]
 [7. 6.]]


In [10]:
# BASIC SLICING AND INDEXING
import numpy as np  
a = np.arange(20)

print("a[15] =", a[15])
print("a[-8:17:1] =", a[-8:17:1])
print("a[10:] =", a[10:])

a[15] = 15
a[-8:17:1] = [12 13 14 15 16]
a[10:] = [10 11 12 13 14 15 16 17 18 19]


In [11]:
# ADVANCED INDEXING
import numpy as np
a = np.array( [[1, 2], [3, 4], [5, 6]] )
print( a[[0, 1, 2], [0, 0, 1]] )

[1 3 6]


In [12]:
# MATRIX OPERATIONS IN NUMPY
import numpy as np

x = np.array([[1, 2], [4, 5]])
y = np.array([[7, 8], [9, 10]])

print("Addition:\n", np.add(x, y))
print("Subtraction:\n", np.subtract(x, y))
print("Division:\n", np.divide(x, y))

Addition:
 [[ 8 10]
 [13 15]]
Subtraction:
 [[-6 -6]
 [-5 -5]]
Division:
 [[0.14285714 0.25      ]
 [0.44444444 0.5       ]]


In [13]:
import numpy as np

x = np.array([[1, 2], [4, 5]])
y = np.array([[7, 8], [9, 10]])

print("Element-wise multiplication:\n", np.multiply(x, y))
print("Matrix multiplication:\n", np.dot(x, y))

Element-wise multiplication:
 [[ 7 16]
 [36 50]]
Matrix multiplication:
 [[25 28]
 [73 82]]


In [14]:
import numpy as np

x = np.array([[1, 2], [4, 5]])
y = np.array([[7, 8], [9, 10]])

print("Square root:\n", np.sqrt(x))
print("Sum of all elements:", np.sum(y))

print("Column-wise sum:", np.sum(y, axis=0))
print("Row-wise sum:", np.sum(y, axis=1))
print("Transpose:\n", x.T)

Square root:
 [[1.         1.41421356]
 [2.         2.23606798]]
Sum of all elements: 34
Column-wise sum: [16 18]
Row-wise sum: [15 19]
Transpose:
 [[1 4]
 [2 5]]


In [16]:
#Task : Print Checkboard pattern using numpy and  matrix concept
import numpy as np

n = 8  # size of checkerboard (8x8)

checkerboard = np.zeros((n, n), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1

print(checkerboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [ ]:
#numpy arithmentic operations
import numpy as np
int(x+y)
print(x-y)
print(x*y)
print(x/y)
x=np.array([1,2,3])
y=np.array([4,5,6])
print(x)
print(y)
pr

[1 2 3]
[4 5 6]
[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [2]:
import numpy as np
# Creating NumPy arrays
# 1D array
a1 = np.array([1, 2, 3, 4, 5, 6, 7, 8])

# 2D array
a2 = np.array([[1, 2],
               [3, 4],
               [5, 6],
               [7, 8]])

# 3D array
a3 = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])

print(a1)
print(a2)
print(a3)

[1 2 3 4 5 6 7 8]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
